[package]
name = "mazzaroth-xdr"
version = "0.1.0"
authors = ["Kochavalabs <dev@mazzaroth.io>"]
description = "XDR objects used by Mazzaroth"
license = "MIT"
homepage = "https://github.com/kochavalabs/mazzaroth-xdr"
repository = "https://github.com/kochavalabs/mazzaroth-xdr"
edition = "2018"

include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
xdr-rs-serialize = { git = "ssh://git@github.com/kochavalabs/xdr-rs-serialize.git", branch = "develop"}
xdr-rs-serialize-derive = { git = "ssh://git@github.com/kochavalabs/xdr-rs-serialize.git", branch = "develop"}

[lib]
path = "rust/xdr_generated.rs"
