version: 2

jobs:
  build-js:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: Clean
          command: rm -rf ./js/*
      - run:
          name: Get Deps
          command: npm run get-deps
      - run:
          name: Build Javascript
          command: npm run build-js
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  publish-js-dev:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set Develop Version
          command: git rev-parse develop | cut -c1-10 | xargs -I[] ./node_modules/package-tagger/index.js dev.[]
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --tag develop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-js
      - publish-js-dev:
          requires:
            - build-js
          filters:
            branches:
              only: develop
